### TYPE YOUR NAME HERE: Anna G. Castillo

# ISM 5644 - Programming for Analytics

## Lab Exercise: Introduction to Pandas

### Overview:
This lab covers operations related to reading and manipulating data with Pandas.

### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. The corresponding question text for each code cell is provided above the cell. Once you have completed the lab, you should publish your notebook code (the code in the .ipynb file) as a "Secret Gist" on your GitHub repository and obtain the Gist ID.

### Submission Format:
There are two deliverables of this lab: 1) the Gist ID and 2) the completed .ipynb file. Both of these should be submitted on Canvas using the corresponding lab submission link by the due date indicated on Canvas.

### Important: Do <u>not</u> forget to run the cells before submitting your work.

### Data Description:

The data set that will be used in this lab is named "cerealData.csv". Please download it from the course website. In this data set, each observation corresponds to a particular brand of cereal. The "mfr" column indicates the manufacture, where A = American Home Food Products; G = General Mills; K = Kelloggs; N = Nabisco; P = Post; Q = Quaker Oats; R = Ralston Purina. Type can be cold ("C") or hot ("H"). Ratings are calculated by Consumer Reports. Other column names are self-explanatory and indicate different ingredients in the cereal.

### Questions: Please note that there are multiple steps in each question. You can run each step individually (before moving on to the next one) to make sure that your output is correct.

#### 1. Data Exploration
* Read the file as a DataFrame
* Display the column names
* Display the size (how many rows and columns)
* Display the first 10 rows
* Rename column "mfr" to "manufacturer"
* Drop column "sodium" from the data
* Drop the rows indexed 0 to 5
* Display the first 10 rows
* Display the summary statistics for numeric variables
* Count the number of cereals that each manufacturer has in the data

In [31]:
import pandas as pd
df = pd.read_csv(r'C:\Users\annac\OneDrive - Florida State University\Programming for statistics\cerealData.csv')

In [32]:
df.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'vitamins', 'rating'],
      dtype='object')

In [33]:
df.shape

(77, 12)

In [34]:
df.head(10)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,vitamins,rating
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6,25,68.402973
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8,0,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,25,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0,25,93.704912
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8,25,34.384843
5,Apple_Cinnamon_Cheerios,G,C,110,2,2,180,1.5,10.5,10,25,29.509541
6,Apple_Jacks,K,C,110,2,0,125,1.0,11.0,14,25,33.174094
7,Basic_4,G,C,130,3,2,210,2.0,18.0,8,25,37.038562
8,Bran_Chex,R,C,90,2,1,200,4.0,15.0,6,25,49.120253
9,Bran_Flakes,P,C,90,3,0,210,5.0,13.0,5,25,53.313813

In [35]:
df = df.rename(columns={'mfr':'manufacturer'})
df

,name,manufacturer,type,calories,protein,fat,sodium,fiber,carbo,sugars,vitamins,rating
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6,25,68.402973
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8,0,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,25,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0,25,93.704912
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8,25,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,25,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,27.753301
74,Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3,25,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,25,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8,25,36.187559

In [36]:
df = df.drop(['sodium'],axis=1)
df

,name,manufacturer,type,calories,protein,fat,fiber,carbo,sugars,vitamins,rating
0,100%_Bran,N,C,70,4,1,10.0,5.0,6,25,68.402973
1,100%_Natural_Bran,Q,C,120,3,5,2.0,8.0,8,0,33.983679
2,All-Bran,K,C,70,4,1,9.0,7.0,5,25,59.425505
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,14.0,8.0,0,25,93.704912
4,Almond_Delight,R,C,110,2,2,1.0,14.0,8,25,34.384843
...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,0.0,21.0,3,25,39.106174
73,Trix,G,C,110,1,1,0.0,13.0,12,25,27.753301
74,Wheat_Chex,R,C,100,3,1,3.0,17.0,3,25,49.787445
75,Wheaties,G,C,100,3,1,3.0,17.0,3,25,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,1,1.0,16.0,8,25,36.187559

In [37]:
df = df.drop([0,1,2,3,4,5])
df

,name,manufacturer,type,calories,protein,fat,fiber,carbo,sugars,vitamins,rating
6,Apple_Jacks,K,C,110,2,0,1.0,11.0,14,25,33.174094
7,Basic_4,G,C,130,3,2,2.0,18.0,8,25,37.038562
8,Bran_Chex,R,C,90,2,1,4.0,15.0,6,25,49.120253
9,Bran_Flakes,P,C,90,3,0,5.0,13.0,5,25,53.313813
10,Cap'n'Crunch,Q,C,120,1,2,0.0,12.0,12,25,18.042851
...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,0.0,21.0,3,25,39.106174
73,Trix,G,C,110,1,1,0.0,13.0,12,25,27.753301
74,Wheat_Chex,R,C,100,3,1,3.0,17.0,3,25,49.787445
75,Wheaties,G,C,100,3,1,3.0,17.0,3,25,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,1,1.0,16.0,8,25,36.187559

In [38]:
df.head(10)

,name,manufacturer,type,calories,protein,fat,fiber,carbo,sugars,vitamins,rating
6,Apple_Jacks,K,C,110,2,0,1.0,11.0,14,25,33.174094
7,Basic_4,G,C,130,3,2,2.0,18.0,8,25,37.038562
8,Bran_Chex,R,C,90,2,1,4.0,15.0,6,25,49.120253
9,Bran_Flakes,P,C,90,3,0,5.0,13.0,5,25,53.313813
10,Cap'n'Crunch,Q,C,120,1,2,0.0,12.0,12,25,18.042851
11,Cheerios,G,C,110,6,2,2.0,17.0,1,25,50.764999
12,Cinnamon_Toast_Crunch,G,C,120,1,3,0.0,13.0,9,25,19.823573
13,Clusters,G,C,110,3,2,2.0,13.0,7,25,40.400208
14,Cocoa_Puffs,G,C,110,1,1,0.0,12.0,13,25,22.736446
15,Corn_Chex,R,C,110,2,0,0.0,22.0,3,25,41.445019

In [39]:
df.describe()

,calories,protein,fat,fiber,carbo,sugars,vitamins,rating
count,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000
mean,108.450704,2.492958,0.943662,1.805634,15.246479,7.028169,28.873239,41.772505
std,17.940209,1.093791,0.908489,1.570067,3.556557,4.468850,23.009271,12.578225
min,50.000000,1.000000,0.000000,0.000000,9.000000,0.000000,0.000000,18.042851
25%,100.000000,2.000000,0.000000,0.000000,12.500000,3.000000,25.000000,32.690838
50%,110.000000,2.000000,1.000000,1.500000,15.000000,7.000000,25.000000,40.400208
75%,110.000000,3.000000,1.000000,3.000000,17.000000,11.000000,25.000000,50.276222
max,160.000000,6.000000,3.000000,6.000000,23.000000,15.000000,100.000000,74.472949

In [40]:
df['manufacturer'].value_counts()

manufacturer
K    21
G    21
P     9
R     7
Q     7
N     5
A     1
Name: count, dtype: int64

#### 2. Selecting from the Data
* Display the sugar amount of "Froot_Loops" (under the "sugars" column)
* Change the "rating" of "Cap'n'Crunch" to 100.0 (since it is the best cereal ever)
* Slice the first 10 observations and the first 5 columns from the data and display the values (do <u>not</u> update the existing data frame)
    * Hint: You can use .iloc() for this purpose.

In [49]:
df_froots= df.loc[df['name']=='Froot_Loops','sugars']
df_froots

24    13
Name: sugars, dtype: int64

In [51]:
df_capt = df.loc[df['name'] == "Cap'n'Crunch", 'rating'] = 100.0
df

,name,manufacturer,type,calories,protein,fat,fiber,carbo,sugars,vitamins,rating
6,Apple_Jacks,K,C,110,2,0,1.0,11.0,14,25,33.174094
7,Basic_4,G,C,130,3,2,2.0,18.0,8,25,37.038562
8,Bran_Chex,R,C,90,2,1,4.0,15.0,6,25,49.120253
9,Bran_Flakes,P,C,90,3,0,5.0,13.0,5,25,53.313813
10,Cap'n'Crunch,Q,C,120,1,2,0.0,12.0,12,25,100.000000
...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,0.0,21.0,3,25,39.106174
73,Trix,G,C,110,1,1,0.0,13.0,12,25,27.753301
74,Wheat_Chex,R,C,100,3,1,3.0,17.0,3,25,49.787445
75,Wheaties,G,C,100,3,1,3.0,17.0,3,25,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,1,1.0,16.0,8,25,36.187559

In [52]:
sliced_df = df.iloc[0:10, 0:5]
sliced_df

                     name manufacturer type  calories  protein
6             Apple_Jacks            K    C       110        2
7                 Basic_4            G    C       130        3
8               Bran_Chex            R    C        90        2
9             Bran_Flakes            P    C        90        3
10           Cap'n'Crunch            Q    C       120        1
11               Cheerios            G    C       110        6
12  Cinnamon_Toast_Crunch            G    C       120        1
13               Clusters            G    C       110        3
14            Cocoa_Puffs            G    C       110        1
15              Corn_Chex            R    C       110        2

#### 3. Filtering
* Display the name, sugar level, and rating of cereals that contain more than 10 grams of sugar
* Find the average rating of the cereals above (i.e., those that contain more than 10 grams of sugar). Compare this number to the average rating of cereals that contain less than 10 grams of sugar.
* Display cereal names, manufacturer names, and rating levels of cereals that contain more than the average calorie amount
* Drop the observations that were manufactured by "Ralston Purina" (indicated as "R" in the manufacturer column)
    * Hint: You can also interpret this statement as selecting all observations that were NOT manufactured by "Ralston Purina"
* Select and display all observations that were manufactured by "General Mills" (indicated as "G") AND that have a rating greater than the average rating score in the data
    * Hint: Remember to use the "&" symbol (instead of AND) when combining multiple conditions in Pandas.

In [53]:
high_sugar_cereals = df.loc[df['sugars'] > 10, ['name', 'sugars', 'rating']]
high_sugar_cereals

                               name  sugars      rating
6                       Apple_Jacks      14   33.174094
10                     Cap'n'Crunch      12  100.000000
14                      Cocoa_Puffs      13   22.736446
17                        Corn_Pops      12   35.782791
18                    Count_Chocula      13   22.396513
24                      Froot_Loops      13   32.207582
25                   Frosted_Flakes      11   31.435973
28                    Fruitful_Bran      12   41.015492
29                   Fruity_Pebbles      12   28.025765
30                     Golden_Crisp      15   35.252444
35                 Honey_Graham_Ohs      11   21.871292
37                       Honey-comb      11   28.742414
42                     Lucky_Charms      12   26.734515
44   Muesli_Raisins_Dates_&_Almonds      11   37.136863
45  Muesli_Raisins_Peaches_&_Pecans      11   34.139765
46             Mueslix_Crispy_Blend      13   30.313351
52            Post_Nat._Raisin_Bran      14   37.840594
58                      Raisin_Bran      12   39.259197
66                           Smacks      15   31.230054
70                Total_Raisin_Bran      14   28.592785
73                             Trix      12   27.753301

In [55]:
avg_rating_HighSugar = df.loc[df['sugars'] > 10, 'rating'].mean()
avg_rating_LowSugar = df.loc[df['sugars'] < 10, 'rating'].mean()
avg_rating_HighSugar
avg_rating_LowSugar

np.float64(47.46842273913044)

In [56]:
high_cal_cereals = df.loc[df['calories'] > df['calories'].mean(), ['name', 'manufacturer', 'rating']]
high_cal_cereals

                                    name manufacturer      rating
6                            Apple_Jacks            K   33.174094
7                                Basic_4            G   37.038562
10                          Cap'n'Crunch            Q  100.000000
11                              Cheerios            G   50.764999
12                 Cinnamon_Toast_Crunch            G   19.823573
13                              Clusters            G   40.400208
14                           Cocoa_Puffs            G   22.736446
15                             Corn_Chex            R   41.445019
17                             Corn_Pops            K   35.782791
18                         Count_Chocula            G   22.396513
19                    Cracklin'_Oat_Bran            K   40.448772
21                               Crispix            K   46.895644
24                           Froot_Loops            K   32.207582
25                        Frosted_Flakes            K   31.435973
27  Fruit_&_Fibre_Dates_Walnuts_and_Oats            P   40.917047
28                         Fruitful_Bran            K   41.015492
29                        Fruity_Pebbles            P   28.025765
31                        Golden_Grahams            G   23.804043
33                            Grape-Nuts            P   53.371007
34                    Great_Grains_Pecan            P   45.811716
35                      Honey_Graham_Ohs            Q   21.871292
36                    Honey_Nut_Cheerios            G   31.072217
37                            Honey-comb            P   28.742414
38           Just_Right_Crunchy__Nuggets            K   36.523683
39                Just_Right_Fruit_&_Nut            K   36.471512
40                                   Kix            G   39.241114
42                          Lucky_Charms            G   26.734515
44        Muesli_Raisins_Dates_&_Almonds            R   37.136863
45       Muesli_Raisins_Peaches_&_Pecans            R   34.139765
46                  Mueslix_Crispy_Blend            K   30.313351
48                      Nut&Honey_Crunch            K   29.924285
49             Nutri-Grain_Almond-Raisin            K   40.692320
51                  Oatmeal_Raisin_Crisp            G   30.450843
52                 Post_Nat._Raisin_Bran            P   37.840594
58                           Raisin_Bran            K   39.259197
61                             Rice_Chex            R   41.998933
62                         Rice_Krispies            K   40.560159
66                                Smacks            K   31.230054
67                             Special_K            K   53.131324
69                     Total_Corn_Flakes            G   38.839746
70                     Total_Raisin_Bran            G   28.592785
72                               Triples            G   39.106174
73                                  Trix            G   27.753301
76                   Wheaties_Honey_Gold            G   36.187559

In [57]:
df = df.loc[df['manufacturer'] != 'R', :]
df

,name,manufacturer,type,calories,protein,fat,fiber,carbo,sugars,vitamins,rating
6,Apple_Jacks,K,C,110,2,0,1.0,11.0,14,25,33.174094
7,Basic_4,G,C,130,3,2,2.0,18.0,8,25,37.038562
9,Bran_Flakes,P,C,90,3,0,5.0,13.0,5,25,53.313813
10,Cap'n'Crunch,Q,C,120,1,2,0.0,12.0,12,25,100.000000
11,Cheerios,G,C,110,6,2,2.0,17.0,1,25,50.764999
...,...,...,...,...,...,...,...,...,...,...,...
71,Total_Whole_Grain,G,C,100,3,1,3.0,16.0,3,100,46.658844
72,Triples,G,C,110,2,1,0.0,21.0,3,25,39.106174
73,Trix,G,C,110,1,1,0.0,13.0,12,25,27.753301
75,Wheaties,G,C,100,3,1,3.0,17.0,3,25,51.592193
76,Wheaties_Honey_Gold,G,C,110,2,1,1.0,16.0,8,25,36.187559

In [58]:
gm_above_AvgRating = df.loc[(df['manufacturer'] == 'G') & (df['rating'] > df['rating'].mean()), :]
gm_above_AvgRating

,name,manufacturer,type,calories,protein,fat,fiber,carbo,sugars,vitamins,rating
11,Cheerios,G,C,110,6,2,2.0,17.0,1,25,50.764999
71,Total_Whole_Grain,G,C,100,3,1,3.0,16.0,3,100,46.658844
75,Wheaties,G,C,100,3,1,3.0,17.0,3,25,51.592193

#### 4. Grouping
* Group data by the manufacturer and find the average sugar level and the average rating for each group
* Select the observations with high rating (rating > 50) and find out how many were manufactured by each manufacturer.

In [60]:
manudata_avg = df.groupby('manufacturer')[['sugars', 'rating']].mean()
manudata_avg

                sugars     rating
manufacturer
A             3.000000  54.850917
G             7.857143  34.722819
K             8.047619  40.940677
N             1.000000  67.881686
P             8.777778  41.705744
Q             5.285714  55.900198

In [62]:
highRating = df.loc[df['rating'] > 50, 'manufacturer'].value_counts()
highRating

manufacturer
N    5
Q    4
K    4
P    3
G    2
A    1
Name: count, dtype: int64